apiVersion: gcm.vmware.com/v1alpha1
kind: ManagedCluster
metadata:
  name: clusterdemo2
  namespace: demo-app-01
spec:
  topology:
    controlPlane:
      count: 1
      class: guaranteed-xsmall # vmclass to be used for master(s)
      storageClass: project-pacific-storage
    workers:
      count: 1
      class: guaranteed-xsmall # vmclass to be used for workers(s)
      storageClass: project-pacific-storage
  distribution:
    version: v1.15.5+vmware.1.66-guest.1.26
  settings:
    network:
      cni:
        name: calico
      services:
        cidrBlocks: ["198.51.100.0/12"]
      pods:
        cidrBlocks: ["192.0.2.0/16"]
